services:
  middleware-dev:
    container_name: middleware-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
      args:
        ENVIRONMENT: ${ENVIRONMENT}
        POSTGRES_DB_ENABLED: ${POSTGRES_DB_ENABLED:-true}
        DB_INIT_ENABLED: ${DB_INIT_ENABLED:-true}
        REDIS_ENABLED: ${REDIS_ENABLED:-true}
        BACKEND_ENABLED: ${BACKEND_ENABLED:-true}
        FRONTEND_ENABLED: ${FRONTEND_ENABLED:-true}
        CRON_ENABLED: ${CRON_ENABLED:-true}

    env_file:
      - .env

    ports:
      - "9696:9696"
      - "9697:9697"
      - "3333:3333"
      - "5434:5434"
      - "6379:6379"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    develop:
      watch:
        - action: sync
          path: ./backend/analytics_server
          target: /app/backend/analytics_server
          ignore: 
            - venv
            - __pycache__
            - env.example

        - action: rebuild
          path: ./backend/requirements.txt

        - action: rebuild
          path: ./backend/dev-requirements.txt

        - action: rebuild
          path: ./setup_util/supervisord.conf

        - action: rebuild
          path: ./setup_utils/init_db.sh

        - action: rebuild
          path: ./.env

        - action: sync+restart
          path: ./backend/analytics_server/.env.local
          target: /app/backend/analytics_server/.env.local

        - action: sync
          path: ./web-server
          target: /app/web-server
          ignore: 
            - ./web-server/.vscode 
            - ./web-server/node_modules

        - action: rebuild
          path: ./web-server/package.json
