blank_issues_enabled: true
contact_links:
  - name: Slack for Support & Discussions
    url: https://join.slack.com/t/middle-out-group/shared_invite/zt-2hg1b7i04-GdJuchJJ8Wdm8IKX6d2rxA
    about: Hang out with the community of Engineering Managers, Tech Leads, and CTOs.
  - name: Get on a Call
    url: https://calendly.com/middleware-dhruv/30min
    about: Get a tailored demo for your use cases